---
- name: Setup iPXE for GRUB
  block:
    - name: Create iPXE directory
      ansible.builtin.file:
        path: "{{ chroot_path }}/boot/ipxe"
        state: directory
        mode: '0755'

    - name: Download iPXE efi binary
      ansible.builtin.get_url:
        url: https://{{ nginx_url }}/ipxe.efi
        dest: "{{ chroot_path }}/boot/ipxe/ipxe.efi"

    - name: Download the iPXE script
      ansible.builtin.get_url:
        url: https://{{ nginx_url }}/boot.ipxe
        dest: "{{ chroot_path }}/boot/ipxe/boot.ipxe"

    - name: Add PXE boot entry
      ansible.builtin.blockinfile:
        path: "{{ chroot_path }}/etc/grub.d/06_ipxe"
        block: |
          #!/bin/sh
          exec tail -n +3 $0
          menuentry 'Network Boot (iPXE)' --id=ipxeboot {
              echo 'Loading iPXE...'
              chainloader /boot/ipxe/ipxe.efi dhcp && chain /boot/ipxe/boot.ipxe
          }
        create: yes
        mode: '0755'
        owner: root
        group: root

    - name: Update GRUB configuration
      ansible.builtin.command:
        cmd: chroot {{ chroot_path }} grub-mkconfig -o /boot/grub/grub.cfg
      args:
        chdir: "{{ chroot_path }}"
      register: grub_update
      changed_when: grub_update.stdout != ''
      failed_when: grub_update.rc != 0