---
- name: Install required packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ required_packages }}"

- name: Enable Wake-on-LAN on all interfaces
  shell: |
    for iface in $(ls /sys/class/net/); do
      ethtool -s "$iface" wol g 2>/dev/null
    done
  ignore_errors: yes

- name: Reboot to iPXE
  ansible.builtin.shell:
    cmd: "grub-reboot 'Network Boot (iPXE)' && reboot"
  ignore_unreachable: yes
  ignore_errors: yes

- name: Wait for the server to come back after reboot
  ansible.builtin.wait_for_connection:
    timeout: 600
  ignore_unreachable: yes
