---
- name: Verify the boot mode (UEFI or BIOS)
  stat:
    path: /sys/firmware/efi/efivars
  register: boot_mode

- name: Set fact for boot mode msg
  set_fact:
    boot_mode_message: "{{ 'Booted in UEFI mode' if boot_mode.stat.exists else 'Booted in BIOS mode' }}"

- name: Display boot mode
  debug:
    msg: "{{ boot_mode_message }}"

- name: Check internet connection
  uri:
    url: http://archlinux.org
    return_content: no
  register: internet_check

- name: Fail if no internet connection
  fail:
    msg: "Unable to connect to archlinux.org"
  when: internet_check.status != 200

# - name: Load the keymap
#   ansible.builtin.command:
#     cmd: "loadkeys {{ keymap }}"

- name: Set NTP
  ansible.builtin.shell:
    cmd: "timedatectl set-ntp true"

- name: Check that NTP is enabled
  ansible.builtin.shell:
    cmd: "timedatectl status | grep 'clock synchronized: yes'"
  register: time_sync_check

- name: Fail if clock is not synchronized
  fail:
    msg: "Clock is not synchronized"
  when: time_sync_check.rc != 0

