---
- name: Verify the boot mode (UEFI or BIOS)
  stat:
    path: /sys/firmware/efi/efivars
  register: boot_mode

- name: Set fact for boot mode msg
  set_fact:
    boot_mode_message: "{{ 'Booted in UEFI mode' if boot_mode.stat.exists else 'Booted in BIOS mode' }}"

- name: Display boot mode
  debug:
    msg: "{{ boot_mode_message }}"

- name: Set NTP
  ansible.builtin.shell:
    cmd: "timedatectl set-ntp true"

- name: Wait for NTP to synchronize
  block:
    - name: Check that NTP is enabled
      ansible.builtin.shell:
        cmd: "timedatectl status | grep 'clock synchronized: yes'"
      register: time_sync_check
      retries: 5
      delay: 5
      until: time_sync_check.rc == 0
  rescue:
    - name: Disable NTP
      ansible.builtin.shell:
        cmd: "timedatectl set-ntp false"
    - name: Enable NTP
      ansible.builtin.shell:
        cmd: "timedatectl set-ntp true"
    - name: Fail if clock is not synchronized
      fail:
        msg: "Clock is not synchronized"
      when: time_sync_check.rc != 0


- name: Fail if clock is not synchronized
  fail:
    msg: "Clock is not synchronized"
  when: time_sync_check.rc != 0
