#SPDX-License-Identifier: MIT-0
---
# defaults file for init

git_ssh_key_path: "/home/archusr/.ssh/git_provisioning_key"
provisioning_ssh_key_path: "/home/archusr/.ssh/provisioning_key"
provisioning_api_repo: "git@github.com:asdf57/provisioning-server.git"
provisioning_api_ipv4: "10.2.0.2"
inventory_repo: "git@github.com:asdf57/inventory.git"
provisioning_api_version: "main"
inventory_version: "main"

# Docker network driver (ipvlan or macvlan)
network_driver: "macvlan"

interface: "enp7s0"

# IPVLAN driver settings
ipvlan_subnet: "10.1.1.0/24"
ipvlan_gateway: "10.1.1.1"
ipvlan_mode: "l2"

# MACVLAN driver settings
macvlan_subnet: "10.1.1.0/24"
macvlan_gateway: "10.1.1.1"
macvlan_mode: "bridge"

dhcp_range: ""
cloudflare_domain: "REDACTED"
cloudflare_api_key: "REDACTED"
cloudflare_email: "REDACTED"
zerossl_email: "REDACTED"
zerossl_eab_kid: "REDACTED"
zerossl_eab_hmac_key: "REDACTED"
cert_authority: "zerossl"

nginx_ipv4: "10.1.1.123"
nginx_acme_label: "REDACTED"

server_api_ipv4: "10.1.1.124"

vault_ipv4: "10.1.1.125"
vault_acme_label: "REDACTED"

user_uid: 1000
user_gid: 1000
