- name: Install kube
  hosts: all
  become: yes
  gather_facts: yes
  tasks:
    # - name: Install prereqs
    #   include_role:
    #     name: kube
    #     tasks_from: install_prereqs

    - name: Install kube
      include_role:
        name: kube
        tasks_from: install
