- name: Initialize the cluster
  hosts: localhost
  tasks:
    - name: Clean up
      import_role:
        name: init
        tasks_from: clean
      become: true
      tags: 
        - clean

    - name: Run
      import_role:
        name: init
        tasks_from: main
      tags: 
        - build
