- name: Initialize the cluster
  hosts: localhost
  vars:
    ansible_python_interpreter: >-
      {{ lookup('env', 'VENV_PYTHON') if inventory_hostname == 'localhost' else '/usr/bin/python3' }}
  tasks:
    - name: Clean up
      import_role:
        name: init
        tasks_from: clean
      become: true
      tags: 
        - clean

    - name: Run
      import_role:
        name: init
        tasks_from: main
      tags: 
        - build
