- name: API provision setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set up servers in API
      include_role:
        name: provision
        tasks_from: create_server
      tags:
        - setup

- name: Infrastructure setup
  hosts: all
  gather_facts: false
  tasks:
    - name: General
      include_role:
        name: provision
        tasks_from: init_server
      tags:
        - setup

- name: Provision
  hosts: all
  tasks:
    - name: Perform prereqs
      include_role:
        name: provision
        tasks_from: prereqs

    - name: Wipe the disk
      include_role:
        name: provision
        tasks_from: wipe

    - name: Setup the disk
      include_role:
        name: provision
        tasks_from: partition

    - name: Bootstrap setup
      include_role:
        name: provision
        tasks_from: bootstrap

    # - name: Setup SSH on the disk
    #   include_role:
    #     name: provision
    #     tasks_from: ssh_setup