- name: Provision
  hosts: all
  vars:
    ansible_python_interpreter: >-
      {{ lookup('env', 'VENV_PYTHON') if inventory_hostname == 'localhost' else '/usr/bin/python3' }}
  tasks:
    - name: Perform prereqs
      include_role:
        name: provision
        tasks_from: prereqs

    - name: Wipe the disk
      include_role:
        name: provision
        tasks_from: wipe

    - name: Setup the disk
      include_role:
        name: provision
        tasks_from: partition

    - name: Setup the system
      include_role:
        name: provision
        tasks_from: setup
