---
- name: Format EFI partition
  ansible.builtin.filesystem:
    fstype: "{{ efi_partition_fs }}"
    dev: "{{ disk_device }}{{ efi_partition_number }}"

- name: Format swap partition
  ansible.builtin.filesystem:
    fstype: "{{ swap_partition_fs }}"
    dev: "{{ disk_device }}{{ swap_partition_number }}"
  when: has_swap_partition

- name: Format general partitions
  ansible.builtin.filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ disk_device }}{{ item.number }}"
  loop: "{{ general_partitions }}"
