- name: Format EFI partition
  ansible.builtin.filesystem:
    fstype: "vfat"
    dev: "{{ disk_device }}{{ efi_partition_number }}"

- name: Check if swap is already enabled
  ansible.builtin.shell: "swapon --show=NAME | grep -w '{{ disk_device }}{{ swap_partition_number }}'"
  register: swap_status
  changed_when: false
  failed_when: swap_status.rc not in [0, 1]

- name: Format the swap partition
  ansible.builtin.command:
    cmd: mkswap "{{ disk_device }}{{ swap_partition_number }}"
  when: has_swap_partition and swap_status.rc != 0

- name: Enable the swap partition
  ansible.builtin.command:
    cmd: swapon "{{ disk_device }}{{ swap_partition_number }}"
  when: has_swap_partition and swap_status.rc != 0

- name: Format general partitions
  ansible.builtin.filesystem:
    fstype: "{{ item.fs }}"
    dev: "{{ disk_device }}{{ item.number }}"
  loop: "{{ general_partitions }}"
