# disk_partitioning role
---
- name: Create GPT partition table
  community.general.parted:
    device: "{{ disk_device }}"
    label: gpt

- name: Create EFI partition
  community.general.parted:
    device: "{{ disk_device }}"
    number: "{{ efi_partition_number }}"
    part_type: primary
    filesystem: "{{ efi_partition_fs }}"
    state: "{{ efi_partition_state }}"
    start: "{{ efi_partition_start }}"
    end: "{{ efi_partition_end }}"
    unit: "{{ efi_partition_unit }}"
    align: "{{ efi_partition_align }}"
    flags: "{{ efi_partition_flags }}"

- name: Create swap partition (if defined)
  community.general.parted:
    device: "{{ disk_device }}"
    number: "{{ swap_partition_number }}"
    part_type: primary
    filesystem: "{{ swap_partition_fs }}"
    state: "{{ swap_partition_state }}"
    start: "{{ swap_partition_start }}"
    end: "{{ swap_partition_end }}"
    unit: "{{ swap_partition_unit }}"
    align: "{{ swap_partition_align }}"
    flags: "{{ swap_partition_flags }}"
  when: has_swap_partition

- name: Create general partitions
  community.general.parted:
    device: "{{ disk_device }}"
    number: "{{ item.number }}"
    part_type: primary
    filesystem: "{{ item.fs }}"
    state: "{{ item.state }}"
    start: "{{ item.start }}"
    end: "{{ item.end }}"
    unit: "{{ item.unit }}"
    align: "{{ item.align }}"
    flags: "{{ item.flags }}"
  loop: "{{ general_partitions }}"
