all:
  hosts:
    desktop:
      ansible_host: 10.1.1.254
      ansible_port: 60022
      primary_mac: 58:11:22:19:87:78
      ansible_user: root
    macmini:
      ansible_host: 192.168.1.91
      ansible_port: 22
      primary_mac: c0:ea:c3:63:1e:94
      ansible_user: root
    zima:
      ansible_host: 10.1.1.250
      ansible_port: 22
      primary_mac: 00:e0:4c:34:97:8f
      ansible_user: root
    beelink:
      ansible_host: 10.1.1.254
      ansible_port: 22
      primary_mac: e8:ff:1e:d4:03:fa
      ansible_user: root
    rpi:
      ansible_host: 10.1.1.253
      ansible_port: 22
      primary_mac: d8:3a:dd:74:ef:f2
      ansible_user: raspusr

  children:
    kube_coords:
      hosts:
        rpi:

    kube_workers:
      hosts:
        desktop:
        macmini:
        zima:
        beelink:
