servers:
  hosts:
    desktop:
      ansible_host: 192.168.1.49
      ansible_port: 60022
      primary_mac: 58:11:22:19:87:78
    macmini:
      ansible_host: 192.168.1.91
      ansible_port: 22
      primary_mac: c0:ea:c3:63:1e:94
    zima:
      ansible_host: 192.168.1.84
      ansible_port: 22
      primary_mac: 00:e0:4c:34:97:8f
    beelink:
      ansible_host: 192.168.1.75
      ansible_port: 22
      primary_mac: e8:ff:1e:d4:03:fa
    rpi:
      ansible_host: 192.168.1.19
      ansible_port: 22
      primary_mac: d8:3a:dd:74:ef:f2
