- name: Check if docker-compose file exists
  ansible.builtin.stat:
    path: "{{ role_path }}/files/docker-compose.yml"
  register: docker_compose_file

- name: Bring down the docker compose stack
  community.docker.docker_compose_v2:
    project_src: "{{ role_path }}/files"
    project_name: infra
    state: absent
    remove_volumes: yes
    remove_images: all
    remove_orphans: yes
  when: docker_compose_file.stat.exists

- name: Cleanup acme files
  block:
    - name: Delete the acme.sh directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/acme/acme.sh"
        state: absent

- name: Cleanup the nginx files
  block:
    - name: Delete directories
      ansible.builtin.file:
        path: "{{ role_path }}/files/nginx/files/{{ item.0 }}_{{ item.1 }}"
        state: absent
      with_nested:
        - [arch, debian]
        - [netboot, iso]

    - name: Remove the templated default.conf
      ansible.builtin.file:
        path: "{{ role_path }}/files/nginx/files/default.conf"
        state: absent

    - name: Remove the ipxe.iso file
      ansible.builtin.file:
        path: "{{ role_path }}/files/nginx/files/ipxe.iso"
        state: absent

    - name: Remove the ipxe.efi file
      ansible.builtin.file:
        path: "{{ role_path }}/files/nginx/files/ipxe.efi"
        state: absent

- name: Cleanup the vault files
  block:
    - name: Delete the vault internal directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/vault/internal"
        state: absent

    - name: Delete the vault logs directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/vault/logs"
        state: absent

    - name: Delete the vault secrets directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/vault/secrets"
        state: absent

    - name: Delete the vault vault_stuff directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/vault/vault_stuff"
        state: absent

- name: Cleanup the provisioning-api
  block:
    - name: Delete the provisioning-api directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/provisioning-api"
        state: absent

- name: Delete the docker-compose.yml file
  ansible.builtin.file:
    path: "{{ role_path }}/files/docker-compose.yml"
    state: absent

- name: Cleanup the registry files
  block:
    - name: Delete the generated registry config file
      ansible.builtin.file:
        path: "{{ role_path }}/files/registry/config/config.yml"
        state: absent

    - name: Delete the registry data directory
      ansible.builtin.file:
        path: "{{ role_path }}/files/registry/data"
        state: absent
