---
- name: Mount primary root partition to /mnt
  ansible.posix.mount:
    src: "{{ disk_device }}{{ general_partitions[0].number }}"
    path: /mnt
    state: mounted
    fstype: "{{ general_partitions[0].fs }}"

- name: Create mount point for boot partition
  ansible.builtin.file:
    path: /mnt/boot/efi
    state: directory

- name: Mount the EFI partition to /boot/efi
  ansible.posix.mount:
    src: "{{ disk_device }}{{ efi_partition_number }}"
    path: /mnt/boot/efi
    state: mounted
    fstype: vfat

# - name: Mount additional partitions (if defined)
#   ansible.posix.mount:
#     src: "{{ disk_device }}{{ item.number }}"
#     path: /mnt
#     state: mounted
#     fstype: "{{ general_partitions[0].fs }}"
#   loop: "{{ general_partitions[1:] }}"
#   when: general_partitions | length > 0
