ansible_host: ""
ansible_user: ""
ansible_port: ""
ansible_ssh_private_key_file: ""
disk_device: ""
boot_partition_min: ""
boot_partition_max: ""
swap_partition_min: ""
swap_partition_max: ""
root_partition_min: ""
root_partition_max: ""
root_filesystem: ""
root_password: ""
locale: ""
hostname: ""
username: ""
password: ""