# group_vars/all.yml

# Ansible connection details
ansible_host: "{{ config.ansible.host }}"
ansible_user: "{{ config.ansible.user }}"
ansible_port: "{{ config.ansible.port }}"
ansible_ssh_private_key_file: "{{ config.ansible.private_key }}"

# Disk configuration
disk_device: "{{ config.disk.device }}"
disk_size: "{{ config.disk.size }}"

# EFI Partition
efi_partition: "{{ config.disk.partitions | selectattr('type', 'equalto', 'efi') | first }}"
efi_partition_number: "{{ efi_partition.number }}"
efi_partition_align: "{{ efi_partition.align }}"
efi_partition_flags: "{{ efi_partition.flags }}"
efi_partition_fs: "{{ efi_partition.fs }}"
efi_partition_label: "{{ efi_partition.label }}"
efi_partition_name: "{{ efi_partition.name }}"
efi_partition_start: "{{ efi_partition.start }}"
efi_partition_end: "{{ efi_partition.end }}"
efi_partition_resize: "{{ efi_partition.resize }}"
efi_partition_state: "{{ efi_partition.state }}"
efi_partition_unit: "{{ efi_partition.unit }}"

# Swap Partition (Optional)
swap_partition: "{{ config.disk.partitions | selectattr('type', 'equalto', 'swap') | first }}"
has_swap_partition: "{{ swap_partition is not none }}"
swap_partition_number: "{{ swap_partition.number if has_swap_partition else '' }}"
swap_partition_align: "{{ swap_partition.align if has_swap_partition else '' }}"
swap_partition_flags: "{{ swap_partition.flags if has_swap_partition else '' }}"
swap_partition_fs: "{{ swap_partition.fs if has_swap_partition else '' }}"
swap_partition_label: "{{ swap_partition.label if has_swap_partition else '' }}"
swap_partition_name: "{{ swap_partition.name if has_swap_partition else '' }}"
swap_partition_start: "{{ swap_partition.start if has_swap_partition else '' }}"
swap_partition_end: "{{ swap_partition.end if has_swap_partition else '' }}"
swap_partition_resize: "{{ swap_partition.resize if has_swap_partition else '' }}"
swap_partition_state: "{{ swap_partition.state if has_swap_partition else '' }}"
swap_partition_unit: "{{ swap_partition.unit if has_swap_partition else '' }}"

# General (Root) Partitions (List)
general_partitions: "{{ config.disk.partitions | selectattr('type', 'equalto', 'general') | list }}"

# Users
users: "{{ config.users | default([]) | list }}"

# Packages
packages: "{{ config.packages | default([]) | list }}"
