
- name: Arch Linux Pre-Installation
  hosts: all
  become: yes
  vars:
    disk_device: ""
    boot_partition_min: ""
    boot_partition_max: ""
    swap_partition_min: ""
    swap_partition_max: ""
    root_partition_min: ""
    root_partition_max: ""
    root_filesystem: ""
  pre_tasks:
    - name: Ensure variables are defined by user
      assert:
        that:
          - disk_device != ""
          - boot_partition_min != ""
          - boot_partition_max != ""
          - swap_partition_min != ""
          - swap_partition_max != ""
          - root_partition_min != ""
          - root_partition_max != ""
          - root_filesystem != ""
        fail_msg: "Please define all variables before running the playbook"
        success_msg: "All variables are defined"

  tasks:
    - name: Set the console keyboard layout
      command: localectl set-keymap us

    - name: Set the console keyboard layout
      command: localectl set-keymap us

    - name: Verify the boot mode
      shell: |
        if [[ $(ls /sys/firmware/efi/efivars) ]]; then
          echo "Booted in UEFI mode"
        else
          echo "Booted in BIOS mode"
        fi

    - name: Check internet connection
      command: ping -c 1 archlinux.org

    - name: Update the system clock
      command: timedatectl set-ntp true

    - name: Partition the disks
      block:
        - name: Create GPT partition table
          command: parted {{ disk_device }} -- mklabel gpt
        - name: Create /boot partition
          block:
            - name: Create the /boot partition
              command: parted {{ disk_device }} -- mkpart primary {{ boot_partition_min }} {{ boot_partition_max }}
            - name: Set boot flag on /boot partition
              command: parted {{ disk_device }} -- set 1 boot on
            - name: Set esp flag on /boot partition
              command: parted {{ disk_device }} -- set 1 esp on
        - name: Create swap partition
          block:
            - name: Create the swap partition
              command: parted {{ disk_device }} -- mkpart primary linux-swap {{ swap_partition_min }} {{ swap_partition_max }}
            - name: Set swap flag on swap partition
              command: parted {{ disk_device }} -- set 2 swap on
        - name: Create root partition
          command: parted {{ disk_device }} -- mkpart primary {{ root_filesystem }} {{ root_partition_min }} {{ root_partition_max }}

    - name: Format the partitions
      block:
        - name: Format /boot partition
          command: mkfs.fat -F32 {{ disk_device }}1
        - name: Format swap partition
          block:
            - name: Format the swap partition
              command: mkswap {{ disk_device }}2
            - name: Enable the swap partition
              command: swapon {{ disk_device }}2
        - name: Format root partition
          command: mkfs.{{ root_filesystem }} {{ disk_device }}3

    - name: Mount the file systems
      block:
        - name: Mount root partition
          command: mount {{ disk_device }}3 /mnt
        - name: Mount /boot partition
          block:
          - name: Create /boot mount point
            command: mkdir /mnt/boot
          - name: Mount the /boot partition
            command: mount {{ disk_device }}1 /mnt/boot
