resources:
- name: repo
  type: git
  source:
    uri: https://github.com/asdf57/arch-provisioner.git
    branch: main

jobs:
  - name: test
    plan:
      - get: repo
        trigger: true
      - task: testing
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: alpine
              tag: 3.20
          inputs:
              - name: repo
          run:
            path: sh
            args:
            - -exc
            - | 
              echo hi