#!/usr/bin/env bash

set -euo pipefail

local_env_file="${1:-.env.local}"

if [[ -f "$local_env_file" ]]; then
  # shellcheck disable=SC1090
  source "$local_env_file"
fi

if [[ "$(uname -s)" != "Linux" ]]; then
  echo "bootstrap_host.sh currently supports Linux nodes only." >&2
  exit 1
fi

detect_docker_gid() {
  local gid

  gid="$(getent group docker | cut -d: -f3 || true)"
  if [[ -n "$gid" ]]; then
    printf '%s\n' "$gid"
    return
  fi

  if [[ -S /var/run/docker.sock ]]; then
    stat -c '%g' /var/run/docker.sock
    return
  fi

  echo "Unable to detect DOCKER_GID. Ensure Docker is installed and running." >&2
  exit 1
}

detect_network_interface() {
  local iface

  iface="$(ip route show default 2>/dev/null | awk '/default/ {print $5; exit}')"
  if [[ -n "$iface" ]]; then
    printf '%s\n' "$iface"
    return
  fi

  iface="$(ip -o link show | awk -F': ' '$2 != "lo" {print $2; exit}')"
  if [[ -n "$iface" ]]; then
    printf '%s\n' "$iface"
    return
  fi

  echo "Unable to detect NETWORK_INTERFACE." >&2
  exit 1
}

HOST_DATA_PATH="${HOST_DATA_PATH:-/srv/homelab}"
MOUNTED_DATA_PATH="${MOUNTED_DATA_PATH:-$HOST_DATA_PATH}"
HOST_GIT_PROVISIONING_KEY_FILE="${HOST_GIT_PROVISIONING_KEY_FILE:-$HOME/.ssh/git_provisioning_key}"
HOST_PROVISIONING_KEY_FILE="${HOST_PROVISIONING_KEY_FILE:-$HOME/.ssh/provisioning_key}"
DOCKER_GID="${DOCKER_GID:-$(detect_docker_gid)}"
NETWORK_INTERFACE="${NETWORK_INTERFACE:-$(detect_network_interface)}"

existing_homelab_gid="$(getent group homelab | cut -d: -f3 || true)"
if [[ -n "$existing_homelab_gid" ]]; then
  HOMELAB_GID="$existing_homelab_gid"
else
  HOMELAB_GID="${HOMELAB_GID:-2000}"
  sudo groupadd -g "$HOMELAB_GID" homelab
fi

if ! id -nG "$USER" | grep -qw homelab; then
  sudo usermod -aG homelab "$USER"
fi

sudo mkdir -p "$HOST_DATA_PATH"
sudo chown root:homelab "$HOST_DATA_PATH"
sudo chmod 2775 "$HOST_DATA_PATH"

mkdir -p "$(dirname "$HOST_GIT_PROVISIONING_KEY_FILE")"
mkdir -p "$(dirname "$HOST_PROVISIONING_KEY_FILE")"

if [[ ! -f "$HOST_GIT_PROVISIONING_KEY_FILE" ]]; then
  ssh-keygen -t ed25519 -f "$HOST_GIT_PROVISIONING_KEY_FILE" -N "" -C "git-provisioning-key"
fi

if [[ ! -f "$HOST_PROVISIONING_KEY_FILE" ]]; then
  ssh-keygen -t ed25519 -f "$HOST_PROVISIONING_KEY_FILE" -N "" -C "device-provisioning-key"
fi

tmp_file="$(mktemp)"
cat > "$tmp_file" <<EOF
# Generated by scripts/bootstrap_host.sh
HOST_DATA_PATH=$HOST_DATA_PATH
MOUNTED_DATA_PATH=$MOUNTED_DATA_PATH
HOST_GIT_PROVISIONING_KEY_FILE=$HOST_GIT_PROVISIONING_KEY_FILE
HOST_PROVISIONING_KEY_FILE=$HOST_PROVISIONING_KEY_FILE
DOCKER_GID=$DOCKER_GID
HOMELAB_GID=$HOMELAB_GID
NETWORK_INTERFACE=$NETWORK_INTERFACE
EOF

mv "$tmp_file" "$local_env_file"

echo ":: Wrote host-local bootstrap values to $local_env_file"
