#!/usr/bin/env python3

# Read in data, read in template, render template, write out rendered template
import os
import sys
import yaml
from jinja2 import Environment, FileSystemLoader

def render_template(template_path, data):
    env = Environment(loader=FileSystemLoader(os.path.dirname(template_path)))
    template = env.get_template(os.path.basename(template_path))
    rendered_template = template.render(data)
    print(rendered_template)

if __name__ == "__main__":
    template = sys.argv[1]
    data = sys.argv[2]

    with open(data, "r") as f:
        data = yaml.safe_load(f)

    render_template(template, data)
