---
- name: Setup DNS resolution by adding nameserver to /etc/resolv.conf
  ansible.builtin.lineinfile:
    path: /etc/resolv.conf
    line: "nameserver 8.8.8.8"
    insertbefore: EOF
    state: present
