#SPDX-License-Identifier: MIT-0
---
# defaults file for harbor
harbor_ip: 10.1.1.11
type: "loadBalancer"
common_name: "harbor.ryuugu.dev"
harbor_secret_name: "harbor-secret"
notary_secret_name: "notary-secret"
